### ISSUE TITLE
code

### ISSUE THREAD

**Issue by shenqian0926** [lmiconsulting/cosasi#5]
Hello, this is Spotting Culprits in Epidemics: How many and Which ones? This paper NetSleuth this method source code

**Comment by lucasmccabe** [comment]
> Hello, this is Spotting Culprits in Epidemics: How many and Which ones? This paper NetSleuth this method source code

Hello, thank you for reaching out. I'm not sure I understand the issue - can you clarify? Thanks!

**Comment by shenqian0926** [comment]
> > Hello, this is Spotting Culprits in Epidemics: How many and Which ones? This paper NetSleuth this method source code
> 
> Hello, thank you for reaching out. I'm not sure I understand the issue - can you clarify? Thanks!

I am studying the paper《Spotting Culprits in Epidemics: How many and Which ones》，I would like to ask whether the code you provided is the source code of this paper？I would like to ask whether the code you provided is the source code of this paper？

**Comment by lucasmccabe** [comment]
> > > Hello, this is Spotting Culprits in Epidemics: How many and Which ones? This paper NetSleuth this method source code
> > 
> > 
> > Hello, thank you for reaching out. I'm not sure I understand the issue - can you clarify? Thanks!
> 
> I am studying the paper《Spotting Culprits in Epidemics: How many and Which ones》，I would like to ask whether the code you provided is the source code of this paper？I would like to ask whether the code you provided is the source code of this paper？

Ah, got it. This repo is not the official source code for this paper, but we do implement the NETSLEUTH algorithm described therein. I'm not aware of an official repo for the paper.

You can find the documentation for our NETSLEUTH implementation [here](https://cosasi.readthedocs.io/en/latest/apiref_pages/source_inference_pages/single_source_pages/netsleuth.html) and the corresponding code [here](https://github.com/lmiconsulting/cosasi/blob/main/cosasi/source_inference/single_source/netsleuth.py).

**Comment by lucasmccabe** [comment]
> > > > > Hello, this is Spotting Culprits in Epidemics: How many and Which ones? This paper NetSleuth this method source code
> > > > 
> > > > 
> > > > Hello, thank you for reaching out. I'm not sure I understand the issue - can you clarify? Thanks!
> > > 
> > > 
> > > I am studying the paper《Spotting Culprits in Epidemics: How many and Which ones》，I would like to ask whether the code you provided is the source code of this paper？I would like to ask whether the code you provided is the source code of this paper？
> > 
> > 
> > Ah, got it. This repo is not the official source code for this paper, but we do implement the NETSLEUTH algorithm described therein. I'm not aware of an official repo for the paper.
> > You can find the documentation for our NETSLEUTH implementation [here](https://cosasi.readthedocs.io/en/latest/apiref_pages/source_inference_pages/single_source_pages/netsleuth.html) and the corresponding code [here](https://github.com/lmiconsulting/cosasi/blob/main/cosasi/source_inference/single_source/netsleuth.py).
> 
> May I ask where is the file that provides the data set using the NETSLEUTH.py file, and which program gets the results after model training

I would recommend walking through the [tutorial](https://cosasi.readthedocs.io/en/latest/tutorial.html), which may clarify some things. An important note is that no model training is needed.

I think you're asking about the inputs to NETSLEUTH. The algorithm accepts an infection subgraph and a substrate graph. The substrate graph is the network the infection process ran on. The infection subgraph is the subgraph of the substrate graph consisting of infected nodes.

Your infection subgraph can be observed from real-world data or generated using our [simulation module](https://cosasi.readthedocs.io/en/latest/tutorial_pages/running_simulation.html).

**Comment by shenqian0926** [comment]
> > > > > > Hello, this is Spotting Culprits in Epidemics: How many and Which ones? This paper NetSleuth this method source code
> > > > > 
> > > > > 
> > > > > Hello, thank you for reaching out. I'm not sure I understand the issue - can you clarify? Thanks!
> > > > 
> > > > 
> > > > I am studying the paper《Spotting Culprits in Epidemics: How many and Which ones》，I would like to ask whether the code you provided is the source code of this paper？I would like to ask whether the code you provided is the source code of this paper？
> > > 
> > > 
> > > Ah, got it. This repo is not the official source code for this paper, but we do implement the NETSLEUTH algorithm described therein. I'm not aware of an official repo for the paper.
> > > You can find the documentation for our NETSLEUTH implementation [here](https://cosasi.readthedocs.io/en/latest/apiref_pages/source_inference_pages/single_source_pages/netsleuth.html) and the corresponding code [here](https://github.com/lmiconsulting/cosasi/blob/main/cosasi/source_inference/single_source/netsleuth.py).
> > 
> > 
> > May I ask where is the file that provides the data set using the NETSLEUTH.py file, and which program gets the results after model training
> 
> I would recommend walking through the [tutorial](https://cosasi.readthedocs.io/en/latest/tutorial.html), which may clarify some things. An important note is that no model training is needed.
> 
> I think you're asking about the inputs to NETSLEUTH. The algorithm accepts an infection subgraph and a substrate graph. The substrate graph is the network the infection process ran on. The infection subgraph is the subgraph of the substrate graph consisting of infected nodes.
> 
> Your infection subgraph can be observed from real-world data or generated using our [simulation module](https://cosasi.readthedocs.io/en/latest/tutorial_pages/running_simulation.html).

But I can't find your main file, how do you run it

**Comment by lucasmccabe** [comment]
> But I can't find your main file, how do you run it

What is "it"? If you're asking how to run the forward simulation, this is described in the tutorial [here](https://cosasi.readthedocs.io/en/latest/tutorial_pages/running_simulation.html). If you're asking how to run a source inference algorithm, this is introduced in the tutorial [here](https://cosasi.readthedocs.io/en/latest/tutorial_pages/source_inference.html).

**Comment by shenqian0926** [comment]
> > 但是我找不到你的主文件，你怎么运行它
> 
> “它”是什么？如果你询问如何运行前向模拟，则[此处](https://cosasi.readthedocs.io/en/latest/tutorial_pages/running_simulation.html)的教程中对此进行了介绍。如果您询问如何运行源推理算法，则[此处](https://cosasi.readthedocs.io/en/latest/tutorial_pages/source_inference.html)的教程中对此进行了介绍。

I want to generate a propagation graph based on the data set I'm going to use, and your tutorial should be a simulated one. I was wondering if it's in the source inference section that we convert the graphs generated by the simulation directly to the graphs generated by the dataset? And according to your tutorial, where should this statement run。
![image](https://github.com/lmiconsulting/cosasi/assets/79795597/5cf138bb-ac0b-4614-bbd7-7c5f6ab1fb74)

**Comment by shenqian0926** [comment]
> > But I can't find your main file, how do you run it
> 
> What is "it"? If you're asking how to run the forward simulation, this is described in the tutorial [here](https://cosasi.readthedocs.io/en/latest/tutorial_pages/running_simulation.html). If you're asking how to run a source inference algorithm, this is introduced in the tutorial [here](https://cosasi.readthedocs.io/en/latest/tutorial_pages/source_inference.html).
such as
![image](https://github.com/lmiconsulting/cosasi/assets/79795597/66355746-f588-46b5-9270-d97bdc378a16)

How do I feed the data into the code

**Comment by lucasmccabe** [comment]
The above error indicates you haven't provided an infection subgraph. Do you have one?

If you are looking for help debugging, can you provide the specific code snippet you are attempting and the full traceback for the error?

> How do I feed the data into the code

What is the data? Please be as specific as possible. Here, you need an infection subgraph I and a substrate graph G. It looks like you might not be providing I.

**Comment by shenqian0926** [comment]
> 上述错误表示您尚未提供感染子图。你有吗？
> 
> 如果您正在寻找调试帮助，您能否提供您正在尝试的特定代码片段以及错误的完整回溯？
> 
> > 如何将数据输入代码
> 
> 数据是什么？请尽可能具体。在这里，您需要一个感染子图I和一个底物图G。看起来你可能没有提供我。

**Comment by shenqian0926** [comment]
> > 上述错误表示您尚未提供感染子图。你有吗？
> > 如果您正在寻找调试帮助，您能否提供您正在尝试的特定代码片段以及错误的完整回溯？
> > > 如何将数据输入代码
> > 
> > 
> > 数据是什么？请尽可能具体。在这里，您需要一个感染子图I和一个底物图G。看起来你可能没有提供我。

![image](https://github.com/lmiconsulting/cosasi/assets/79795597/454491a4-ad37-4e43-8c0e-100a629ee14b)
![image](https://github.com/lmiconsulting/cosasi/assets/79795597/cdcad623-5977-4065-8f1c-0dde0138b2ed)

**Comment by lucasmccabe** [comment]
> > > 上述错误表示您尚未提供感染子图。你有吗？
> > > 如果您正在寻找调试帮助，您能否提供您正在尝试的特定代码片段以及错误的完整回溯？
> > > > 如何将数据输入代码
> > > 
> > > 
> > > 数据是什么？请尽可能具体。在这里，您需要一个感染子图I和一个底物图G。看起来你可能没有提供我。
> 
> ![image](https://user-images.githubusercontent.com/79795597/246409985-454491a4-ad37-4e43-8c0e-100a629ee14b.png) ![image](https://user-images.githubusercontent.com/79795597/246410165-cdcad623-5977-4065-8f1c-0dde0138b2ed.png)

This shows how you're constructing I, but does not show where you're calling the NETSLEUTH algorithm. Are you passing the infection subgraph to it?

If possible, please provide enough code for me to be able to reproduce your issue.

**Comment by shenqian0926** [comment]
> > > > 上述错误表示您尚未提供感染子图。你有吗？
> > > > 如果您正在寻找调试帮助，您能否提供您正在尝试的特定代码片段以及错误的完整回溯？
> > > > > 如何将数据输入代码
> > > > 
> > > > 
> > > > 数据是什么？请尽可能具体。在这里，您需要一个感染子图I和一个底物图G。看起来你可能没有提供我。
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/79795597/246409985-454491a4-ad37-4e43-8c0e-100a629ee14b.png) ![图像](https://user-images.githubusercontent.com/79795597/246410165-cdcad623-5977-4065-8f1c-0dde0138b2ed.png)
> 
> 这显示了你如何构造 I，但没有显示你在哪里调用 NETSLEUTH 算法。您是否将感染子图传递给它？
> 
> 如果可能，请提供足够的代码，以便我能够重现您的问题。

I'm not really sure how you call the netsleuth code, is all your code only the definition of these methods, but not the code that calls such as netsleuth methods? I only in your netsleuth code added to deal with the data set part of the code, did not call this, I see your explanation to write that line of code, what is the meaning, is to me to write another running main file, and then source inference algorithm in it.

**Comment by lucasmccabe** [comment]
> I only in your netsleuth code added to deal with the data set part of the code, did not call this, I see your explanation to write that line of code, what is the meaning, is to me to write another running main file, and then source inference algorithm in it.

In your code, it looks like you have a function that takes arguments I and G, but you're defining I inside that function. That appears to be the source of the error you're getting.

> I'm not really sure how you call the netsleuth code, is all your code only the definition of these methods, but not the code that calls such as netsleuth methods?

cosasi is a library, so you can call these algorithms by importing cosasi and calling the algorithms in your source code. It's a similar workflow to what you would do if you want to access the functionality of any other package, like numpy.

For instance, if you import cosasi, you should be able to call NETSLEUTH via single_source_result = cosasi.single_source.netsleuth(I, G) or similar. single_source_result will be a result object that contains the outcome of the algorithm.

So in your code, it looks like you are defining G as a global variable. You can move the code you use to define I outside of the netsleuth function (so I is global, too) and then call a source inference algorithm from there.

Does that help?

**Comment by shenqian0926** [comment]
> > 我只是在你的netsleuth代码中加入了处理数据集的部分代码，没有调用这个，我看你的解释写那行代码，是什么意思，就是给我写另一个运行的主文件，然后在里面源推理算法。
> 
> 在你的代码中，看起来你有一个接受参数 I 和 G 的函数，但你在那个函数中定义了 I。这似乎是您得到的错误的根源。
> 
> > 我不太确定您如何调用 netsleuth 代码，您的所有代码都只是这些方法的定义，而不是调用 netsleuth 方法的代码吗？
> 
> cosasi 是一个库，因此您可以通过导入 cosasi 并在源代码中调用算法来调用这些算法。这与您想要访问任何其他包（如 numpy）的功能时执行的操作类似。
> 
> 例如，如果你导入cosasi，你应该能够通过single_source_result = cosasi.single_source.netsleuth（I，G）或类似的东西调用NETSLEUTH。single_source_result将是包含算法结果的结果对象。
> 
> 因此，在您的代码中，您似乎将 G 定义为全局变量。您可以将用于定义 I 的代码移到 netsleuth 函数之外（因此 I 也是全局的），然后从那里调用源推理算法。
> 
> 这有帮助吗？
That is to say, I write another code, import the cosasi library, and then call this netsleuth function, I see and estimator, whether to call this indicator function, then should put this code in which file, can you give an example

**Comment by shenqian0926** [comment]
> > 我只是在你的netsleuth代码中加入了处理数据集的部分代码，没有调用这个，我看你的解释写那行代码，是什么意思，就是给我写另一个运行的主文件，然后在里面源推理算法。
> 
> 在你的代码中，看起来你有一个接受参数 I 和 G 的函数，但你在那个函数中定义了 I。这似乎是您得到的错误的根源。
> 
> > 我不太确定您如何调用 netsleuth 代码，您的所有代码都只是这些方法的定义，而不是调用 netsleuth 方法的代码吗？
> 
> cosasi 是一个库，因此您可以通过导入 cosasi 并在源代码中调用算法来调用这些算法。这与您想要访问任何其他包（如 numpy）的功能时执行的操作类似。
> 
> 例如，如果你导入cosasi，你应该能够通过single_source_result = cosasi.single_source.netsleuth（I，G）或类似的东西调用NETSLEUTH。single_source_result将是包含算法结果的结果对象。
> 
> 因此，在您的代码中，您似乎将 G 定义为全局变量。您可以将用于定义 I 的代码移到 netsleuth 函数之外（因此 I 也是全局的），然后从那里调用源推理算法。
> 
> 这有帮助吗？

![image](https://github.com/lmiconsulting/cosasi/assets/79795597/2db03404-31a3-4762-a07f-74744ab44ddf)
how to deal with it？

**Comment by shenqian0926** [comment]
> > 我只是在你的netsleuth代码中加入了处理数据集的部分代码，没有调用这个，我看你的解释写那行代码，是什么意思，就是给我写另一个运行的主文件，然后在里面源推理算法。
> 
> 在你的代码中，看起来你有一个接受参数 I 和 G 的函数，但你在那个函数中定义了 I。这似乎是您得到的错误的根源。
> 
> > 我不太确定您如何调用 netsleuth 代码，您的所有代码都只是这些方法的定义，而不是调用 netsleuth 方法的代码吗？
> 
> cosasi 是一个库，因此您可以通过导入 cosasi 并在源代码中调用算法来调用这些算法。这与您想要访问任何其他包（如 numpy）的功能时执行的操作类似。
> 
> 例如，如果你导入cosasi，你应该能够通过single_source_result = cosasi.single_source.netsleuth（I，G）或类似的东西调用NETSLEUTH。single_source_result将是包含算法结果的结果对象。
> 
> 因此，在您的代码中，您似乎将 G 定义为全局变量。您可以将用于定义 I 的代码移到 netsleuth 函数之外（因此 I 也是全局的），然后从那里调用源推理算法。
> 
> 这有帮助吗？

I did not use the single_source function, this must report an error, how to solve it

**Comment by shenqian0926** [comment]
> > I only in your netsleuth code added to deal with the data set part of the code, did not call this, I see your explanation to write that line of code, what is the meaning, is to me to write another running main file, and then source inference algorithm in it.
> 
> In your code, it looks like you have a function that takes arguments I and G, but you're defining I inside that function. That appears to be the source of the error you're getting.
> 
> > I'm not really sure how you call the netsleuth code, is all your code only the definition of these methods, but not the code that calls such as netsleuth methods?
> 
> cosasi is a library, so you can call these algorithms by importing cosasi and calling the algorithms in your source code. It's a similar workflow to what you would do if you want to access the functionality of any other package, like numpy.
> 
> For instance, if you import cosasi, you should be able to call NETSLEUTH via single_source_result = cosasi.single_source.netsleuth(I, G) or similar. single_source_result will be a result object that contains the outcome of the algorithm.
> 
> So in your code, it looks like you are defining G as a global variable. You can move the code you use to define I outside of the netsleuth function (so I is global, too) and then call a source inference algorithm from there.
> 
> Does that help?

![image](https://github.com/lmiconsulting/cosasi/assets/79795597/8fe89e5a-1692-4c00-9003-9f1265ea4916)
Now I want to recall, precision and F1_score three indicators, how should I predict the "predicted" parameter
![image](https://github.com/lmiconsulting/cosasi/assets/79795597/2fe0be58-1c9f-4f08-a4ab-9473ea3dd26a)

**Comment by lucasmccabe** [comment]
First, I'll say that in this domain, recall, precision, and F1 score are not necessarily standard evaluation metrics. Two more common ones - source rank and distance from source - are already implemented in the `.evaluate` function. your line `result.evaluate(contagion.get_source())` is a good start, but you need to assign that value to a variable so you can access it later (this is exemplified in the [Evaluating Results](https://cosasi.readthedocs.io/en/latest/tutorial_pages/evaluating_results.html#evaluating-results) part of the tutorial).

As for your specific error, can you provide the full traceback? That way, we can tell where the error is arising.

**Comment by shenqian0926** [comment]
> 首先，我要说的是，召回率、精度和 F1 分数不一定是该领域的标准评估指标。两个更常见的 - 源秩和与源的距离 - 已经在函数中实现。您的行是一个良好的开端，但您需要将该值分配给变量，以便以后可以访问它（本教程的[评估结果](https://cosasi.readthedocs.io/en/latest/tutorial_pages/evaluating_results.html#evaluating-results)部分对此进行了示例）。`.evaluate``result.evaluate(contagion.get_source())`
> 
> 至于您的具体错误，您能提供完整的回溯吗？这样，我们就可以知道错误在哪里出现。

![image](https://github.com/lmiconsulting/cosasi/assets/79795597/22063fdc-db5c-4446-8869-137c6b3b65a7)
![image](https://github.com/lmiconsulting/cosasi/assets/79795597/1cc54499-c0f8-42bd-92ec-c2e8b4333b96)

**Comment by lucasmccabe** [comment]
Hi @shenqian0926, I recommend reading the [relevant tutorial section](https://cosasi.readthedocs.io/en/latest/tutorial_pages/evaluating_results.html#evaluating-results) and/or [API reference for Source Results](https://cosasi.readthedocs.io/en/latest/apiref_pages/source_inference_pages/source_results.html), which will clarify syntax and available functionality.

If your question is "why am I getting this error," the answer is that, in line 79, you are attempting to assign the attribute `top_sol` of the function `result.evaluate` to the variable `predicted`. In that line, you are not executing the `.evaluate()` function, you are just asking for its attribute `top_sol`, which does not exist (hence the AttributeError). I do not know what `result.evaluate.top_sol` is meant to be.

Also, in line 77, you have created a result object, but you have not assigned it to any variable, so it doesn't really "do" anything (although this is not why you're getting the AttributeError).

Let me know if you have a specific question.
